name: subtitle_wrapper_package
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 2.1.0
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  better_player:
    git:
      url: https://github.com/kkoken/betterplayer
      ref: master
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  http_parser: ^4.0.1

dev_dependencies:
  bloc_test: ^9.0.3
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  mocktail: ^0.3.0

flutter:
